"""minor changes to improve performance

Revision ID: a8b626fd50a7
Revises: 96ba5b8b0b2f
Create Date: 2025-10-01 17:06:10.978650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8b626fd50a7'
down_revision: Union[str, Sequence[str], None] = '96ba5b8b0b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'categories',
               existing_type=postgresql.ENUM('WORK', 'PERSONAL', 'STUDY', 'FITNESS', 'SHOPPING', 'HEALTH', 'HOBBY', 'OTHER', name='todo_category'),
               nullable=False)
    op.create_index('ix_todos_user_id', 'todos', ['user_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_todos_user_id', table_name='todos')
    op.alter_column('todos', 'categories',
               existing_type=postgresql.ENUM('WORK', 'PERSONAL', 'STUDY', 'FITNESS', 'SHOPPING', 'HEALTH', 'HOBBY', 'OTHER', name='todo_category'),
               nullable=True)
    # ### end Alembic commands ###
